FROM node:12

EXPOSE 5000

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install 
#--only=production

# Bundle app source
COPY . .

CMD [ "npm", "start" ]